// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingApi.Infrastructure;

#nullable disable

namespace ShippingApi.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    [Migration("20220815203822_AddCountryTable")]
    partial class AddCountryTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Bag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BagNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BagNumber")
                        .IsUnique();

                    b.ToTable("Bags");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Bag");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c78d2ab0-612e-4854-8b59-4f483075a351"),
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = new Guid("5a3a2b55-8f64-432f-aad7-28554e10f241"),
                            Code = "AX",
                            Name = "Aland Islands"
                        },
                        new
                        {
                            Id = new Guid("9093b25d-db91-4afe-b4c0-1dfe4c0d9b7f"),
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = new Guid("749630a9-1c9e-42a4-9aff-ea069ac16133"),
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = new Guid("d06bd687-6f5b-411b-bf35-540ac3a14635"),
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = new Guid("f9b69cf6-8220-449a-976a-176461a42540"),
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = new Guid("367e1e9e-bc32-4336-b36d-8bca31822be9"),
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = new Guid("834be208-8ca5-4c11-8336-57c96609c1e1"),
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = new Guid("bf66644b-1eff-40e9-aaac-bc8e5dce4026"),
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = new Guid("9b522149-e902-47d2-8314-232cac802465"),
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = new Guid("0a99693c-9b26-48eb-94a0-986c6cd36177"),
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = new Guid("43dcd0de-0fe8-4bc3-b2fa-6b05ba26cc03"),
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = new Guid("4b42f515-f3e9-4c28-8bae-b7b69a3c7cd5"),
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = new Guid("5f65235f-d320-4833-adc6-67631bd37f38"),
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = new Guid("e8e8d773-bba6-4607-9b81-c10d66c37317"),
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = new Guid("274327c7-a7e6-4ed5-88a4-6876bfb64f09"),
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = new Guid("d9aec02e-2622-43cb-b70b-38f19a60f12d"),
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = new Guid("5678bc91-ba2b-4cf2-ba10-ae4deb23efe7"),
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = new Guid("ce320fc7-1421-4995-970f-c050d275a0b9"),
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = new Guid("02cddf42-df8d-47d8-abde-56a693264da6"),
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = new Guid("305abcc1-d2c5-424a-9954-8bd592f6c0b1"),
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = new Guid("252e98b6-1f05-4e1c-a87b-eb750675bc7e"),
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = new Guid("58c5c1dc-0697-4d17-98aa-cb1eb1554f1f"),
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = new Guid("ed43499a-abf3-4a3a-be4d-e9c82037d0c8"),
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = new Guid("0efead88-1bd2-4a69-aa02-da2093320d75"),
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = new Guid("46b6b14d-0d06-47c8-9666-4c436aa7a1af"),
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = new Guid("2d7898f8-9307-4576-8f8a-db0a5f2eb0f9"),
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = new Guid("9432c48d-9701-40da-93d0-4927401874bb"),
                            Code = "BQ",
                            Name = "Bonaire Saint Eustatius and Saba"
                        },
                        new
                        {
                            Id = new Guid("ccdadd9a-40f9-4709-93c9-bf2c7f929ebf"),
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = new Guid("2a1ac426-2d84-420c-bac5-af5ae365129c"),
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = new Guid("c630d70b-81b9-4a65-8cf8-7bd88e2d12b6"),
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = new Guid("515686e8-1b0a-4e7b-8b77-048051930a91"),
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = new Guid("c05b3158-0b0b-4e6e-97c8-d3b2a6781daa"),
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = new Guid("34d7f9bd-58f7-47c6-b8d2-cef275561cc3"),
                            Code = "VG",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = new Guid("5916e9f8-9bfa-444f-9879-9ce2d300806d"),
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = new Guid("5ea0541e-9037-4c50-bfbc-f93282f173ae"),
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = new Guid("521b8361-a403-4d4f-9bf0-0f3583714e81"),
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = new Guid("341e0da2-058a-43cf-bc71-f5479a4189d8"),
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = new Guid("b1e61bb7-f1c0-4826-88a1-cad5b0f999e3"),
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = new Guid("020e4d0c-5179-43d4-bdd8-5b7952c53605"),
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = new Guid("e41a7310-f06d-4f51-b31a-da793821eb95"),
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = new Guid("879b084c-8f66-407e-aadc-fd53334b4b82"),
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = new Guid("2ee47afa-e8e6-40e3-9346-6fa084669845"),
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = new Guid("8f978893-7384-488f-9c9a-243a22034391"),
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = new Guid("411f36f7-c8fd-4dcc-964c-ab96a7bdcce7"),
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = new Guid("f90080b2-c6bd-4ab8-bf5e-442450012fd0"),
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = new Guid("d4750d54-1344-4caa-ab61-a7957552f363"),
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("fe0db153-37d9-4e9c-9306-817a1fa25aa4"),
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = new Guid("934de1af-afce-4a8f-aa31-0912957cd366"),
                            Code = "CC",
                            Name = "Cocos Islands"
                        },
                        new
                        {
                            Id = new Guid("1a75cc99-cd4b-4997-afd6-e0738f2b2fc7"),
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("53e9fa6c-10fe-4b83-81fa-759ed39687a8"),
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = new Guid("62656d6b-497f-4752-b903-142b3277b323"),
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = new Guid("50ec6dba-d5ef-4a15-975b-d1f5c22c3791"),
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = new Guid("fe22137d-9964-4a23-853f-0694e679ebd5"),
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = new Guid("ab148a7b-af1d-429f-b9db-8a38945ea85a"),
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = new Guid("95cdd89a-19db-4def-9dd1-333ecea905d2"),
                            Code = "CW",
                            Name = "Curacao"
                        },
                        new
                        {
                            Id = new Guid("f1717e08-6d41-4ffb-be01-864777b76510"),
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = new Guid("32b83b25-565b-4ed5-8537-4a51590df98c"),
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = new Guid("885ca960-f376-4904-879e-3dc330aa587d"),
                            Code = "CD",
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("319725d0-ee10-491e-b67a-aeae8d2a2a4c"),
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = new Guid("78fba52f-3486-4bca-a3d5-0c67c6630443"),
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = new Guid("15147505-e1a5-4fda-88ad-ef0342d9d0e2"),
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = new Guid("4667ca27-936c-4829-93f7-285e8eb7b0ee"),
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = new Guid("94e76938-f5e4-4c52-b089-af96714931a2"),
                            Code = "TL",
                            Name = "East Timor"
                        },
                        new
                        {
                            Id = new Guid("ae2b96b4-87a7-4b1b-a90d-706ffc275929"),
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = new Guid("8e26ebf8-a9d9-4c6a-b0fc-1734965b27ad"),
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = new Guid("f2a11532-f612-44ab-80c2-2482028d5019"),
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = new Guid("6ef87f20-2399-489a-ab56-7bdfe9f7b76f"),
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = new Guid("95cc9bdd-4965-473e-a0b2-dd795c55acc6"),
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = new Guid("cb0e4ed9-a5c8-4ff6-a980-1a768bcd323d"),
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = new Guid("f18ed599-4adb-491a-ae19-8083ec44dbdb"),
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = new Guid("2869413d-cba6-4150-9d74-50b4c93d6413"),
                            Code = "FK",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = new Guid("7c45761e-82cd-4bf0-b88d-222195747789"),
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = new Guid("b75979c7-b93f-42a8-a17a-453456e96d21"),
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = new Guid("66f6ca55-6615-4c67-b4d5-0b299f7b8db2"),
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = new Guid("6e4ec4ce-d123-4e31-a317-a2a9636ace4a"),
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = new Guid("7518c837-8ba7-40fb-b733-c4089c631389"),
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = new Guid("e693fb53-43a6-4c52-99f8-a76276e234d5"),
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = new Guid("f6ef76bb-61bd-475e-9c2f-f11f6083395f"),
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = new Guid("84d35fe2-fdb7-40ac-94dd-c2b9146e2e03"),
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = new Guid("b9c82b04-0c35-435f-a922-9121d0b131d5"),
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = new Guid("2706a61d-fc02-4744-b225-9c9ddb0bba50"),
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = new Guid("d3463a03-06c6-4d0d-afce-e59c30a40670"),
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = new Guid("021c15db-1c34-40e9-af03-d8fd95b55d22"),
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = new Guid("25e35639-9fe6-4c68-8c85-446b00c7103b"),
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = new Guid("58203c3e-3732-454b-a2a4-80125a23943a"),
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = new Guid("045b9e56-7c5b-4460-b3cf-d1ed2af8dd1b"),
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = new Guid("78ad3c5d-873e-4b60-81a9-2f56d9b9421f"),
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = new Guid("8afabbd8-6eef-4649-8448-a0d39f65702e"),
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = new Guid("beff92ec-24c2-4d58-a2bd-61ee63d3a796"),
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = new Guid("a1f9befd-c77f-4ae9-9f1c-1ffbf44a3d85"),
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = new Guid("5505f1f0-734c-4553-8554-2cb2caf4e9de"),
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = new Guid("ab51097a-beac-4c21-b50e-06d85d349614"),
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = new Guid("cf6d633c-f54f-41dd-acf9-31baa248b5e6"),
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = new Guid("d8861e22-1ed4-4452-a837-200c4328125f"),
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = new Guid("433c734e-add9-4128-a4a5-d8e2cac73ec2"),
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = new Guid("9165c62c-1d40-4173-8e5c-f01057d94a28"),
                            Code = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = new Guid("f5d8ea11-5aa0-46ae-9109-4dc8fc32ca66"),
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = new Guid("e02d4087-4f9e-4866-b793-6e00a8f8c223"),
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = new Guid("ab7a2c78-8665-4d8b-9865-587026b909e0"),
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = new Guid("7421da32-0b4a-418f-bb39-f39fcd140362"),
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = new Guid("c64deef5-f6b2-4975-b702-9aac1794f49d"),
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("9f18879a-a1b3-46b1-b115-effdb0082d7f"),
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = new Guid("03519c65-0a42-49ea-99d4-2d075d6777d8"),
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = new Guid("e3c01914-609b-4f07-b937-1a262ce7eebd"),
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = new Guid("76b258c3-7e41-46df-851f-2c84d687e0d4"),
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = new Guid("e853e150-5016-49fa-8df2-b664b4617a99"),
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = new Guid("dd1186f2-81a1-4204-82bd-998e4faf5b43"),
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = new Guid("60ed91af-85f1-4862-9d64-46eda498901d"),
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = new Guid("126295e7-1113-46c2-9fe7-d7697ff3470a"),
                            Code = "CI",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = new Guid("26d506c6-0e42-4022-b497-df284aa80516"),
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = new Guid("6424a525-3a22-4300-82b8-b9177ffbb1cc"),
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("ecb796ba-0020-48ed-9ff5-2d7dfcfbf4fc"),
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = new Guid("010c6d19-c6cf-438e-8e35-d0e75edb44c1"),
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = new Guid("6ead6a45-f729-42e7-9f5b-70437c970199"),
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = new Guid("02315f29-2806-4517-b8f4-a3011336be35"),
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = new Guid("5aba8501-41af-4b4c-aaf4-ac6b74a8cda8"),
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = new Guid("51ad381a-3bd6-41a7-8521-ac0077405bc8"),
                            Code = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = new Guid("9820bdc5-ff40-42e9-83b5-533ce8d35275"),
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = new Guid("3e0dd1f6-00d4-4984-996d-abb648b48ce3"),
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = new Guid("5a4e97c8-83f2-4154-8d60-dfed549253ad"),
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = new Guid("4fa2a81c-b3d9-4c5b-a6bd-406fa074d36e"),
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = new Guid("f590e513-95ec-42b7-9240-062c7cda4868"),
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = new Guid("fd60ad79-10aa-44cf-a2c4-abd29bdd6d81"),
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = new Guid("3e753541-fd64-47af-9a6e-6478090adacd"),
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = new Guid("5153a6e7-b056-4b11-a56c-5e5bc323d3e2"),
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = new Guid("67755bc4-e041-4ee0-ab85-06689632f71c"),
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = new Guid("b39931c3-ae8c-4330-bed0-0c640b172c75"),
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = new Guid("51141eb8-459a-4d8e-b9ca-0602aed42187"),
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = new Guid("67a71039-ab91-47fc-a395-69a1554bd62f"),
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = new Guid("552939da-21ec-495e-a59b-713cd77fcf95"),
                            Code = "MK",
                            Name = "Macedonia"
                        },
                        new
                        {
                            Id = new Guid("1b934370-4433-4d69-a092-14505b60a6f4"),
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = new Guid("dad6a274-e6c6-4ed8-bc23-f1795c482474"),
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = new Guid("671ab069-8299-4059-8d60-5b41e4f1c558"),
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = new Guid("59b7ad30-bb6f-4fb9-bc44-58eb143a1b50"),
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = new Guid("76638bc9-d011-4145-bf02-1576f87bb939"),
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = new Guid("fcb99754-151d-4b36-84d0-da74a9663923"),
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = new Guid("54216853-fac0-4ae7-9a4e-912a63e489ea"),
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = new Guid("4f1d431e-6e09-4f15-ad79-da133354afc5"),
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = new Guid("12d82e02-f6c2-4798-bf87-91b0f2f19a86"),
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = new Guid("88189348-0146-41dc-8107-dc3b68236f7d"),
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = new Guid("51a04d61-e313-4298-ac4d-707b0f824be8"),
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = new Guid("f0b80579-9d19-419d-b1b4-2e45c5238cf9"),
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = new Guid("dbae8e68-743b-4489-87bd-4d55c9b655b6"),
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = new Guid("e32d5907-aea6-41d1-9c85-d6c7179d4133"),
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = new Guid("67d197b0-ddbe-46e2-b9b2-007e1edf9921"),
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = new Guid("20489a9e-a866-4e50-ad19-8cab1ed37c84"),
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = new Guid("992eea7b-0298-49e9-8a2c-ac2ede91b75d"),
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = new Guid("a2327898-6eba-4181-b6d0-0ff4258a005f"),
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = new Guid("a075a982-60d8-42fa-b51c-31251a1af8a7"),
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = new Guid("e17f9089-d34a-493d-96d5-8125820db44a"),
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = new Guid("cfe6fc2b-fa4b-4121-b3b0-99cbba30e35f"),
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = new Guid("faf6c0d1-ee2b-4e19-a731-c480c0ba68a0"),
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = new Guid("e450f713-fd80-4fc1-a881-b551299b17c1"),
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = new Guid("c53fdafe-2256-4e86-86e8-93f915e41e26"),
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = new Guid("aafe5a8f-21b5-4e03-8eb4-49f5bf679a09"),
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = new Guid("579b5918-df2d-4ae2-98b7-36cf0d2f8179"),
                            Code = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = new Guid("f7002427-1e66-40c1-b22f-3bef7f6aa803"),
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = new Guid("f5c2f7fc-59ed-4903-add4-ba60cdbe3985"),
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = new Guid("32d9d116-f2e2-48a5-91a8-bd60a19160eb"),
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = new Guid("94da56cd-e9ae-44c6-8c01-324630ab88f5"),
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = new Guid("f71309dc-138e-4220-ad77-1ddab20965f6"),
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = new Guid("99ac3442-842f-4b0e-b001-2f2a147a1746"),
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = new Guid("6dd54c5e-31f9-49e2-aff3-acb8a813b449"),
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = new Guid("c3aa5e2f-1d54-4c5c-8452-cefa08964db1"),
                            Code = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = new Guid("86aade6a-6ad2-4e25-b9a1-923fffe3ed4f"),
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = new Guid("e159ccb2-831b-47a9-958d-ab47aa9fdaac"),
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = new Guid("60162d63-4fc0-428b-abf5-9b0cfa7f2312"),
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = new Guid("4b543d3c-14ab-4b3f-8ec1-31723cf35847"),
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = new Guid("e22765c4-37b6-4f8a-8be7-069168b7d2a7"),
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = new Guid("81ed7475-98ef-492b-93b9-07cc1e09821c"),
                            Code = "PS",
                            Name = "Palestinian Territory"
                        },
                        new
                        {
                            Id = new Guid("4e000dc1-8a16-4f6a-8cd4-b4f8c84178d8"),
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = new Guid("1109d9c6-dc66-4deb-9399-d524166f6eab"),
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = new Guid("cef6fd1e-fe16-40d0-a2c9-17148fdfb3c1"),
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = new Guid("3b1ac3bc-753a-4687-ba58-f99b0df20927"),
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = new Guid("1b900e20-f78d-435b-966c-8fdfa43c1fa2"),
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = new Guid("45371370-cae1-44ab-9bcb-65c6d69722ec"),
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = new Guid("419c2c51-d52d-4d1e-aa42-93be52d808bb"),
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = new Guid("50cd818a-8650-4486-9284-106a49705e13"),
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = new Guid("1115add0-2364-485b-bcfb-ffaeee2fbf55"),
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = new Guid("7c455e2b-9f54-4755-ab9f-0205d60cf72f"),
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = new Guid("dcffc723-199b-4c54-a7ea-58647dcc706c"),
                            Code = "CG",
                            Name = "Republic of the Congo"
                        },
                        new
                        {
                            Id = new Guid("ecdd5070-8261-48a0-ad67-e954f0325c88"),
                            Code = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = new Guid("ce73a5e5-2e36-469c-8a91-1ca274217e99"),
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = new Guid("bb654cce-255d-4fb4-856a-e266d0ba4c3b"),
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = new Guid("9a5bf306-073b-4c9b-bd11-5903b51db464"),
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = new Guid("897942e2-d6f6-4cb0-b523-4643bdd52c61"),
                            Code = "BL",
                            Name = "Saint Barthelemy"
                        },
                        new
                        {
                            Id = new Guid("d8d5d697-0a30-46f8-b8e1-a8142b031095"),
                            Code = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = new Guid("9c3ac7e0-c51c-40ce-a81f-55d1c8b9802d"),
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = new Guid("68b4e565-35e7-4601-9d1c-7dfa5f1b695e"),
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = new Guid("ffe48143-ef78-4193-a3ad-57910439d48d"),
                            Code = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = new Guid("91542005-1b98-4d38-bb3d-c6fa0d20d368"),
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = new Guid("996f0109-5180-41fb-a972-f89864763ef4"),
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = new Guid("17a3d049-9868-4372-b5ef-904989c02f37"),
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = new Guid("defb7ef4-a691-4bf7-83f1-b4a9f48f0390"),
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = new Guid("82db40ea-eb83-4a53-bcdf-209629d7675f"),
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = new Guid("420bcb23-4fee-4288-b3c1-b1d33a5fcf96"),
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = new Guid("2c7ffdd8-b626-4a92-9d30-025f1d85478a"),
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = new Guid("060ccf46-4171-4f14-a6a3-9d89fad31407"),
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = new Guid("5aafa585-c8c3-4cf1-b694-de77c006a16c"),
                            Code = "CS",
                            Name = "Serbia and Montenegro"
                        },
                        new
                        {
                            Id = new Guid("db5ef375-f778-4a52-b67f-d5882da0da47"),
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = new Guid("bbb119c9-f59a-455b-91df-f9bdfc899861"),
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = new Guid("076f8631-ade3-4ee7-93ab-73b29336ac2c"),
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = new Guid("25d4ce4d-a825-4503-a2c9-0d21d2934882"),
                            Code = "SX",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = new Guid("22a52038-371c-4ff4-b424-0d96e598d40c"),
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = new Guid("a5c8a478-99a3-47e7-acf1-8f22d5f89ea8"),
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = new Guid("e82bad63-87c5-4227-bfc2-6e29d97fcfc1"),
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = new Guid("110b08e3-dd29-4421-a3e4-5eb2e03feeb2"),
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = new Guid("efbf97bc-5df4-401e-aa33-fe96eaf76839"),
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = new Guid("f1221d51-2868-4dfb-b199-c595dbbf02dd"),
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = new Guid("1662994d-09d3-47da-8da9-c8dfc3b31e37"),
                            Code = "KR",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = new Guid("c225c326-5eb3-4e86-8293-df0885678864"),
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = new Guid("dfdee4b9-0871-4c49-8ef5-bb47921be429"),
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = new Guid("1fa1253a-6155-49d1-b02e-ad337c3c475b"),
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = new Guid("ecb16cec-f1c3-42dd-a672-d65706f308fe"),
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = new Guid("2d572f1e-6087-4a69-9c25-13ff8758dd6c"),
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = new Guid("9ca31e28-88b8-4ec0-b482-ba0d39ec22dd"),
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = new Guid("778b3d9b-6b2f-41e0-9d71-7fc943e5895c"),
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = new Guid("6ea53e31-2698-4835-8efc-0c5918025f24"),
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = new Guid("3a6ad880-ab94-4fdc-b7f4-ddf036158003"),
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = new Guid("27a4c12c-ef6f-4f62-b3cb-6d330981485a"),
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = new Guid("c29771b8-e284-4203-8de6-f299a9e252eb"),
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = new Guid("4f189a54-b79e-4209-bc68-0fa69f1fdb9e"),
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = new Guid("82210ba2-e8c2-4831-b233-d059dcbb7179"),
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = new Guid("9c444c45-d922-4267-b2b4-0f4e0d422cff"),
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = new Guid("d4011780-af3b-460b-99fb-9a330e57e224"),
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = new Guid("8c036ca1-6376-4875-86f5-86ea473fd6ae"),
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = new Guid("08886a3c-70f4-454b-bc04-f14b013c27a1"),
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = new Guid("736f469e-4269-46df-b0e1-208abbb880b2"),
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = new Guid("22844636-6508-4a7b-82b5-2f473d19bb26"),
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = new Guid("3df460f6-be3c-45ad-94b4-29b611766b99"),
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = new Guid("31cb8022-b41e-423e-bcaa-49bd32a260bc"),
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = new Guid("a2b5f9c6-6dda-46de-a04e-f36ff0825fdf"),
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = new Guid("0120c779-998b-4dc5-b2fa-bce41a520f78"),
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = new Guid("69752e89-1a3a-440b-8273-edb97ee739ff"),
                            Code = "VI",
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Id = new Guid("0ccb8243-83d7-41b6-b1db-7ca9f455af31"),
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = new Guid("57d096c0-1fcd-4676-9b68-c27f45d58d84"),
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = new Guid("ec301cf4-e6d3-48e0-a49b-e8399ec2f4c0"),
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = new Guid("26b873c3-654d-46bf-b5fe-a68f9fb717e3"),
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = new Guid("3b4556c6-8b42-47e9-adb1-d1432ffec833"),
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = new Guid("03b33a9e-b35c-4108-829b-65111df98ff5"),
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = new Guid("3a538d50-216f-4170-a277-6469e8d703df"),
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = new Guid("f5195a9d-3fba-4d3d-92ed-b56f151b4087"),
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = new Guid("832721e8-6b1a-4ea1-8d6d-270460579dea"),
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = new Guid("04a27ff9-b7b4-4f91-b30f-ef0a8545e283"),
                            Code = "VA",
                            Name = "Vatican"
                        },
                        new
                        {
                            Id = new Guid("fa948058-f3a1-4783-ae4e-070b714dd277"),
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = new Guid("f899fbac-f6d8-4c83-b332-7bb88d92fd8f"),
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = new Guid("5d8aebc8-9906-4849-af74-33ae0f413308"),
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = new Guid("294c3ac0-ffdd-49ac-859a-c95a577c111f"),
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = new Guid("35d65a96-2b4b-4120-9a7c-d0808a1b7cf7"),
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = new Guid("c18f8fca-d696-48ed-8d87-f29f5f582bba"),
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = new Guid("c7ae8f92-026c-4b73-8022-a2b2ce373efe"),
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.Property<Guid>("ParcelBagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParcelNumber")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelBagId");

                    b.HasIndex("ParcelNumber")
                        .IsUnique();

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Airport")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nchar(6)");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.LetterBag", b =>
                {
                    b.HasBaseType("ShippingApi.Infrastructure.Entities.Bag");

                    b.Property<int>("CountOfLetters")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.HasIndex("ShipmentId");

                    b.HasDiscriminator().HasValue("LetterBag");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.ParcelBag", b =>
                {
                    b.HasBaseType("ShippingApi.Infrastructure.Entities.Bag");

                    b.HasIndex("ShipmentId");

                    b.HasDiscriminator().HasValue("ParcelBag");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Parcel", b =>
                {
                    b.HasOne("ShippingApi.Infrastructure.Entities.ParcelBag", "ParcelBag")
                        .WithMany("Parcels")
                        .HasForeignKey("ParcelBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelBag");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.LetterBag", b =>
                {
                    b.HasOne("ShippingApi.Infrastructure.Entities.Shipment", "Shipment")
                        .WithMany("LetterBags")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.ParcelBag", b =>
                {
                    b.HasOne("ShippingApi.Infrastructure.Entities.Shipment", "Shipment")
                        .WithMany("ParcelBags")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Shipment", b =>
                {
                    b.Navigation("LetterBags");

                    b.Navigation("ParcelBags");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.ParcelBag", b =>
                {
                    b.Navigation("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
