// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingApi.Infrastructure;

#nullable disable

namespace ShippingApi.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    [Migration("20220817140834_ChangeCountryTableKey")]
    partial class ChangeCountryTableKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Bag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BagNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BagNumber")
                        .IsUnique();

                    b.ToTable("Bags");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Bag");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Code = "AX",
                            Name = "Aland Islands"
                        },
                        new
                        {
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Code = "AD",
                            Name = "Andorra"
                        },
                        new
                        {
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Code = "BQ",
                            Name = "Bonaire Saint Eustatius and Saba"
                        },
                        new
                        {
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Code = "VG",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Code = "BN",
                            Name = "Brunei"
                        },
                        new
                        {
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Code = "CC",
                            Name = "Cocos Islands"
                        },
                        new
                        {
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Code = "CW",
                            Name = "Curacao"
                        },
                        new
                        {
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Code = "CD",
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Code = "TL",
                            Name = "East Timor"
                        },
                        new
                        {
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Code = "FK",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Code = "HM",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Code = "IR",
                            Name = "Iran"
                        },
                        new
                        {
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Code = "CI",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Code = "XK",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Code = "LA",
                            Name = "Laos"
                        },
                        new
                        {
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Code = "LY",
                            Name = "Libya"
                        },
                        new
                        {
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Code = "MK",
                            Name = "Macedonia"
                        },
                        new
                        {
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Code = "FM",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Code = "MD",
                            Name = "Moldova"
                        },
                        new
                        {
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Code = "ME",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Code = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Code = "KP",
                            Name = "North Korea"
                        },
                        new
                        {
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Code = "PS",
                            Name = "Palestinian Territory"
                        },
                        new
                        {
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Code = "CG",
                            Name = "Republic of the Congo"
                        },
                        new
                        {
                            Code = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Code = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Code = "RW",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Code = "BL",
                            Name = "Saint Barthelemy"
                        },
                        new
                        {
                            Code = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Code = "MF",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Code = "RS",
                            Name = "Serbia"
                        },
                        new
                        {
                            Code = "CS",
                            Name = "Serbia and Montenegro"
                        },
                        new
                        {
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Code = "SX",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Code = "KR",
                            Name = "South Korea"
                        },
                        new
                        {
                            Code = "SS",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Code = "SY",
                            Name = "Syria"
                        },
                        new
                        {
                            Code = "TW",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Code = "TZ",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Code = "VI",
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Code = "VA",
                            Name = "Vatican"
                        },
                        new
                        {
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Code = "VN",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("nchar(2)");

                    b.Property<Guid>("ParcelBagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParcelNumber")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelBagId");

                    b.HasIndex("ParcelNumber")
                        .IsUnique();

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Airport")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nchar(6)");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasColumnType("nchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.LetterBag", b =>
                {
                    b.HasBaseType("ShippingApi.Infrastructure.Entities.Bag");

                    b.Property<int>("CountOfLetters")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 3)
                        .HasColumnType("decimal(8,3)");

                    b.HasIndex("ShipmentId");

                    b.HasDiscriminator().HasValue("LetterBag");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.ParcelBag", b =>
                {
                    b.HasBaseType("ShippingApi.Infrastructure.Entities.Bag");

                    b.HasIndex("ShipmentId");

                    b.HasDiscriminator().HasValue("ParcelBag");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Parcel", b =>
                {
                    b.HasOne("ShippingApi.Infrastructure.Entities.ParcelBag", "ParcelBag")
                        .WithMany("Parcels")
                        .HasForeignKey("ParcelBagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParcelBag");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.LetterBag", b =>
                {
                    b.HasOne("ShippingApi.Infrastructure.Entities.Shipment", "Shipment")
                        .WithMany("LetterBags")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.ParcelBag", b =>
                {
                    b.HasOne("ShippingApi.Infrastructure.Entities.Shipment", "Shipment")
                        .WithMany("ParcelBags")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.Shipment", b =>
                {
                    b.Navigation("LetterBags");

                    b.Navigation("ParcelBags");
                });

            modelBuilder.Entity("ShippingApi.Infrastructure.Entities.ParcelBag", b =>
                {
                    b.Navigation("Parcels");
                });
#pragma warning restore 612, 618
        }
    }
}
